name = input('What is your name?\n')
print('Hello, %s!' % name)
name = input('How are you %s?\n' % name)
print('Good to hear!')
print('My name is Jenna. I am a v0.1 virtual assistant.')
name = input('What may i help you with?')
name = input('Knock Knock.')
name = input('Hello.')
print('Hello world!')
print('...')
name = input('Is...there anything else I may help you with?')
print('Ok.')